import { MaterialCommunityIcons } from '@expo/vector-icons';
import React from 'react';
import { Alert, Pressable, Share, StyleSheet, Text, View } from 'react-native';
import { useAccounts } from '../context/AccountsContext';
import { removeMovement } from '../data/database';
import type { Movement } from '../domain/types';
import { theme } from '../shared/theme';
import { Button, Card, Header, money, Screen } from '../ui/components';
const label = (m: Movement, currency: 'USDT' | 'CUP') => m.kind === 'deposit' ? 'Depósito' : m.kind === 'withdrawal_cup' ? 'Retiro CUP' : currency === 'USDT' ? 'Retiro directo' : 'Retiro';
export function HistoryScreen() {
  const { selected, movements, balance, loading, refresh } = useAccounts();
  const exportText = async () => { if (!selected) return; const rows = movements.slice().reverse().map(m => { const conversion = m.rate ? ` · ${money(m.inputAmount, 'CUP')} ÷ ${m.rate}` : ''; return `${new Date(m.createdAt).toLocaleString('es-ES')} | ${label(m, selected.currency)} | ${m.balanceAmount >= 0 ? '+' : ''}${money(m.balanceAmount, selected.currency)}${conversion}${m.note ? ` | ${m.note}` : ''}`; }); try { await Share.share({ title: `Resumen de ${selected.name}`, message: `${selected.name}\nSaldo inicial: ${money(selected.initialBalance, selected.currency)}\n\n${rows.join('\n') || 'Sin movimientos'}\n\nSaldo actual: ${money(balance, selected.currency)}` }); } catch (error) { Alert.alert('No se pudo exportar', error instanceof Error ? error.message : 'Inténtalo otra vez.'); } };
  const deleteMovement = async (id: number) => { try { await removeMovement(id); } catch (error) { Alert.alert('No se pudo eliminar', error instanceof Error ? error.message : 'Inténtalo otra vez.'); return; } try { await refresh(); } catch (error) { Alert.alert('Movimiento eliminado', `Se eliminó, pero no se pudo actualizar la pantalla. ${error instanceof Error ? error.message : 'Vuelve a abrir la cuenta.'}`); } };
  const confirmDelete = (id: number) => Alert.alert('Eliminar movimiento', 'El saldo se recalculará automáticamente.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Eliminar', style: 'destructive', onPress: () => void deleteMovement(id) }]);
  return <Screen><Header title="Historial" /><Button label={loading ? 'Actualizando…' : 'Exportar resumen en texto'} icon="share-variant-outline" tone="ghost" onPress={exportText} disabled={loading} />{movements.length ? movements.map(m => <Card key={m.id}><View style={styles.row}><View style={[styles.icon, m.balanceAmount >= 0 ? styles.in : styles.out]}><MaterialCommunityIcons name={m.balanceAmount >= 0 ? 'arrow-down' : 'arrow-up'} size={20} color={m.balanceAmount >= 0 ? theme.colors.success : theme.colors.danger} /></View><View style={styles.copy}><Text style={styles.title}>{label(m, selected?.currency ?? 'CUP')}</Text><Text style={styles.meta}>{new Date(m.createdAt).toLocaleString('es-ES')}{m.note ? ` · ${m.note}` : ''}</Text>{m.rate ? <Text style={styles.rate}>{money(m.inputAmount, 'CUP')} a tasa {m.rate}</Text> : null}</View><View style={styles.end}><Text style={[styles.amount, m.balanceAmount < 0 && styles.negative]}>{m.balanceAmount >= 0 ? '+' : ''}{money(m.balanceAmount, selected?.currency ?? 'CUP')}</Text><Pressable accessibilityRole="button" accessibilityLabel="Eliminar movimiento" accessibilityState={{ disabled: loading }} disabled={loading} onPress={() => confirmDelete(m.id)} style={styles.delete}><MaterialCommunityIcons name="trash-can-outline" size={20} color={theme.colors.muted} /></Pressable></View></View></Card>) : <Card><Text style={styles.empty}>Todavía no hay movimientos en esta cuenta.</Text></Card>}</Screen>;
}
const styles = StyleSheet.create({ row: { flexDirection: 'row', alignItems: 'center', gap: 11 }, icon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, in: { backgroundColor: theme.colors.successSoft }, out: { backgroundColor: theme.colors.dangerSoft }, copy: { flex: 1 }, title: { ...theme.type.label }, meta: { ...theme.type.caption, color: theme.colors.muted, marginTop: 3 }, rate: { ...theme.type.caption, color: theme.colors.info, marginTop: 3 }, end: { alignItems: 'flex-end', gap: 3 }, delete: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, amount: { ...theme.type.label, color: theme.colors.success }, negative: { color: theme.colors.danger }, empty: { ...theme.type.body, color: theme.colors.muted, textAlign: 'center', padding: 24 } });
