import React, { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { useAccounts } from '../context/AccountsContext';
import { getRates, saveProfile, saveRates } from '../data/database';
import type { Rates } from '../domain/types';
import { theme } from '../shared/theme';
import { Button, Card, Header, Input, Screen, Sheet } from '../ui/components';
const empty: Rates = { under50: 0, from50: 0, from100: 0, from500: 0 };
export function SettingsScreen() {
  const { profiles, refresh } = useAccounts(); const [rates, setRates] = useState(empty); const [modal, setModal] = useState(false); const [editingId, setEditingId] = useState<number | null>(null); const [name, setName] = useState(''); const [initial, setInitial] = useState('0');
  useEffect(() => { void getRates().then(setRates); }, []);
  const rateField = (key: keyof Rates, label: string) => <Input label={label} value={String(rates[key] || '')} onChangeText={v => setRates(old => ({ ...old, [key]: Number(v.replace(',', '.')) }))} keyboardType="decimal-pad" placeholder="0" />;
  const saveAllRates = async () => { if (Object.values(rates).some(x => !Number.isFinite(x) || x <= 0)) return Alert.alert('Tasas inválidas', 'Todas las tasas deben ser mayores que cero.'); await saveRates(rates); Alert.alert('Listo', 'Las tasas quedaron guardadas.'); };
  const open = (id: number | null) => { const p = profiles.find(x => x.id === id); setEditingId(id); setName(p?.name ?? ''); setInitial(String(p?.initialBalance ?? 0)); setModal(true); };
  const saveAccount = async () => { const value = Number(initial.replace(',', '.')); if (!name.trim()) return Alert.alert('Falta el nombre', 'Escribe el nombre de la cuenta.'); if (!Number.isFinite(value)) return Alert.alert('Saldo inválido', 'Escribe un saldo inicial válido.'); await saveProfile(editingId, name, value); setModal(false); await refresh(); };
  return <Screen><Header title="Ajustes" /><Card><Text style={styles.title}>Tasas CUP → USDT</Text><Text style={styles.help}>Se eligen automáticamente según la cuantía total del retiro.</Text><View style={styles.form}>{rateField('under50', 'Menos de 50 000 CUP')}{rateField('from50', 'De 50 000 a 99 999 CUP')}{rateField('from100', 'De 100 000 a 499 999 CUP')}{rateField('from500', '500 000 CUP o más')}<Button label="Guardar tasas" icon="content-save-outline" onPress={saveAllRates} /></View></Card>
    <View style={styles.section}><View style={styles.sectionCopy}><Text style={styles.title}>Perfiles de cuenta</Text><Text style={styles.help}>Crea tantos perfiles CUP como necesites.</Text></View><Button label="Crear" icon="plus" tone="ghost" onPress={() => open(null)} /></View>{profiles.map(p => <Card key={p.id}><View style={styles.profile}><View style={{ flex: 1 }}><Text style={styles.profileName}>{p.name}</Text><Text style={styles.help}>{p.currency === 'USDT' ? 'Perfil principal con conversión' : 'Contabilidad completa en CUP'}</Text><Text style={styles.current}>Monto actual: {p.currentBalance.toLocaleString('en-US', { minimumFractionDigits: p.currency === 'USDT' ? 3 : 0, maximumFractionDigits: p.currency === 'USDT' ? 3 : 0 })} {p.currency}</Text><Text style={styles.base}>Inicio: {p.initialBalance.toLocaleString('en-US', { minimumFractionDigits: p.currency === 'USDT' ? 3 : 0, maximumFractionDigits: p.currency === 'USDT' ? 3 : 0 })} {p.currency}</Text></View><Button label="Editar" tone="ghost" onPress={() => open(p.id)} /></View></Card>)}
    <Sheet visible={modal} title={editingId ? 'Editar perfil' : 'Nuevo perfil CUP'} onClose={() => setModal(false)}><View style={styles.sheetForm}><Input label="Nombre" value={name} onChangeText={setName} placeholder="Nombre de la cuenta" /><Input label={`Monto inicial en ${profiles.find(x => x.id === editingId)?.currency ?? 'CUP'} (puede ser negativo)`} value={initial} onChangeText={setInitial} keyboardType="numbers-and-punctuation" /><Text style={styles.sheetHint}>Al guardar, este será el monto base. Los movimientos registrados se suman o descuentan desde él.</Text><Button label="Guardar perfil" icon="check" onPress={saveAccount} /><View style={{ height: 8 }} /></View></Sheet>
  </Screen>;
}
const styles = StyleSheet.create({ title: { ...theme.type.title }, help: { ...theme.type.body, color: theme.colors.muted, marginTop: 4 }, form: { gap: 13, marginTop: 16 }, section: { flexDirection: 'row', alignItems: 'center', gap: 8 }, sectionCopy: { flex: 1, minWidth: 0 }, profile: { flexDirection: 'row', alignItems: 'center', gap: 10 }, profileName: { ...theme.type.section }, current: { ...theme.type.label, color: theme.colors.text, marginTop: 8 }, base: { ...theme.type.caption, color: theme.colors.muted, marginTop: 2 }, sheetForm: { gap: 14 }, sheetHint: { ...theme.type.caption, color: theme.colors.info, marginTop: -5 } });
