import React, { useEffect, useRef, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { useAccounts } from '../context/AccountsContext';
import { getRates, saveProfile, saveRates } from '../data/database';
import type { Currency, Rates } from '../domain/types';
import { formatMoney, parseMoneyInput, parseNumberInput } from '../shared/money';
import { theme } from '../shared/theme';
import { Button, Card, Header, Input, Screen, Sheet } from '../ui/components';
const emptyRates: Record<keyof Rates, string> = { under50: '', from50: '', from100: '', from500: '' };
export function SettingsScreen() {
  const { profiles, loading, refresh } = useAccounts(); const [rates, setRates] = useState(emptyRates); const [modal, setModal] = useState(false); const [editingId, setEditingId] = useState<number | null>(null); const [name, setName] = useState(''); const [initial, setInitial] = useState('0'); const [savingRates, setSavingRates] = useState(false); const [savingProfile, setSavingProfile] = useState(false); const savingRatesRef = useRef(false); const savingProfileRef = useRef(false);
  useEffect(() => { void getRates().then(values => setRates({ under50: String(values.under50), from50: String(values.from50), from100: String(values.from100), from500: String(values.from500) })).catch(error => Alert.alert('No se pudieron cargar las tasas', error instanceof Error ? error.message : 'Inténtalo otra vez.')); }, []);
  const rateField = (key: keyof Rates, label: string) => <Input label={label} value={rates[key]} onChangeText={v => setRates(old => ({ ...old, [key]: v }))} keyboardType="decimal-pad" placeholder="0" editable={!savingRates} />;
  const saveAllRates = async () => { if (savingRatesRef.current) return; const values: Rates = { under50: parseNumberInput(rates.under50), from50: parseNumberInput(rates.from50), from100: parseNumberInput(rates.from100), from500: parseNumberInput(rates.from500) }; if (Object.values(values).some(x => !Number.isFinite(x) || x <= 0)) return Alert.alert('Tasas inválidas', 'Todas las tasas deben ser mayores que cero.'); savingRatesRef.current = true; setSavingRates(true); try { await saveRates(values); setRates({ under50: String(values.under50), from50: String(values.from50), from100: String(values.from100), from500: String(values.from500) }); Alert.alert('Listo', 'Las tasas quedaron guardadas y se usarán en el próximo retiro.'); } catch (error) { Alert.alert('No se pudieron guardar las tasas', error instanceof Error ? error.message : 'Inténtalo otra vez.'); } finally { savingRatesRef.current = false; setSavingRates(false); } };
  const open = (id: number | null) => { const p = profiles.find(x => x.id === id); setEditingId(id); setName(p?.name ?? ''); setInitial(String(p?.initialBalance ?? 0)); setModal(true); };
  const accountCurrency: Currency = profiles.find(x => x.id === editingId)?.currency ?? 'CUP';
  const saveAccount = async () => { if (savingProfileRef.current) return; const value = parseMoneyInput(initial, accountCurrency); if (!name.trim()) return Alert.alert('Falta el nombre', 'Escribe el nombre de la cuenta.'); if (!Number.isFinite(value)) return Alert.alert('Saldo inválido', 'Escribe un saldo inicial válido.'); savingProfileRef.current = true; setSavingProfile(true); try { await saveProfile(editingId, name, value); } catch (error) { Alert.alert('No se pudo guardar el perfil', error instanceof Error ? error.message : 'Inténtalo otra vez.'); savingProfileRef.current = false; setSavingProfile(false); return; } setModal(false); try { await refresh(); } catch (error) { Alert.alert('Perfil guardado', `Quedó guardado, pero no se pudo actualizar la pantalla. ${error instanceof Error ? error.message : 'Vuelve a abrir Ajustes.'}`); } finally { savingProfileRef.current = false; setSavingProfile(false); } };
  return <Screen><Header title="Ajustes" /><Card><Text style={styles.title}>Tasas CUP → USDT</Text><Text style={styles.help}>Se eligen automáticamente según la cuantía total del retiro.</Text><Text style={styles.numberHelp}>Puedes usar punto o coma para decimales; escribe los miles sin separador.</Text><View style={styles.form}>{rateField('under50', 'Menos de 50 000 CUP')}{rateField('from50', 'De 50 000 a 99 999 CUP')}{rateField('from100', 'De 100 000 a 499 999 CUP')}{rateField('from500', '500 000 CUP o más')}<Button label={savingRates ? 'Guardando…' : 'Guardar tasas'} icon="content-save-outline" onPress={saveAllRates} disabled={savingRates} /></View></Card>
    <View style={styles.section}><View style={styles.sectionCopy}><Text style={styles.title}>Perfiles de cuenta</Text><Text style={styles.help}>Crea tantos perfiles CUP como necesites.</Text></View><Button label="Crear" icon="plus" tone="ghost" onPress={() => open(null)} disabled={loading} /></View>{profiles.map(p => <Card key={p.id}><View style={styles.profile}><View style={styles.profileCopy}><Text numberOfLines={2} style={styles.profileName}>{p.name}</Text><Text style={styles.help}>{p.currency === 'USDT' ? 'Perfil principal con conversión' : 'Contabilidad completa en CUP'}</Text><Text style={styles.current}>Monto actual: {formatMoney(p.currentBalance, p.currency)}</Text><Text style={styles.base}>Inicio: {formatMoney(p.initialBalance, p.currency)}</Text></View><Button label="Editar" tone="ghost" onPress={() => open(p.id)} disabled={loading} /></View></Card>)}
    <Sheet visible={modal} title={editingId ? 'Editar perfil' : 'Nuevo perfil CUP'} onClose={() => { if (!savingProfileRef.current) setModal(false); }}><View style={styles.sheetForm}><Input label="Nombre" value={name} onChangeText={setName} placeholder="Nombre de la cuenta" editable={!savingProfile} /><Input label={`Monto inicial en ${accountCurrency} (puede ser negativo)`} value={initial} onChangeText={setInitial} keyboardType="numbers-and-punctuation" editable={!savingProfile} /><Text style={styles.numberHelp}>{accountCurrency === 'USDT' ? 'Puedes usar punto o coma para decimales; escribe los miles sin separador.' : 'Los CUP se guardan sin decimales; puedes separar los miles con punto o coma.'}</Text><Text style={styles.sheetHint}>Al guardar, este será el monto base. Los movimientos registrados se suman o descuentan desde él.</Text><Button label={savingProfile ? 'Guardando…' : 'Guardar perfil'} icon="check" onPress={saveAccount} disabled={savingProfile} /><View style={{ height: 8 }} /></View></Sheet>
  </Screen>;
}
const styles = StyleSheet.create({ title: { ...theme.type.title }, help: { ...theme.type.body, color: theme.colors.muted, marginTop: 4 }, numberHelp: { ...theme.type.caption, color: theme.colors.info, marginTop: 6 }, form: { gap: 13, marginTop: 16 }, section: { flexDirection: 'row', alignItems: 'center', gap: 8 }, sectionCopy: { flex: 1, minWidth: 0 }, profile: { flexDirection: 'row', alignItems: 'center', gap: 10 }, profileCopy: { flex: 1, minWidth: 0 }, profileName: { ...theme.type.section }, current: { ...theme.type.label, color: theme.colors.text, marginTop: 8 }, base: { ...theme.type.caption, color: theme.colors.muted, marginTop: 2 }, sheetForm: { gap: 14 }, sheetHint: { ...theme.type.caption, color: theme.colors.info, marginTop: -5 } });
