import { MaterialCommunityIcons } from '@expo/vector-icons';
import DateTimePicker, { type DateTimePickerEvent } from '@react-native-community/datetimepicker';
import { useFocusEffect } from '@react-navigation/native';
import React, { useCallback, useState } from 'react';
import { Alert, AppState, Platform, Share, StyleSheet, Text, View } from 'react-native';
import { useAccounts } from '../context/AccountsContext';
import { buildReport, formatReportText, periodRange, type Period } from '../domain/reporting';
import { theme } from '../shared/theme';
import { Button, Card, Header, money, Screen, Tabs } from '../ui/components';

const periodNames: Record<Period, string> = { day: 'Día', week: 'Semana', month: 'Mes' };
const date = (value: Date) => value.toLocaleDateString('es-ES', { day: '2-digit', month: 'short', year: 'numeric' });

export function SummaryScreen() {
  const { selected, movements, loading } = useAccounts(); const [period, setPeriod] = useState<Period>('day'); const [previous, setPrevious] = useState(false); const [customStart, setCustomStart] = useState<Date | null>(null); const [picker, setPicker] = useState<'date' | 'time' | null>(null);
  const [now, setNow] = useState(() => new Date());
  useFocusEffect(useCallback(() => { const updateClock = () => setNow(new Date()); updateClock(); const timer = setInterval(updateClock, 60000); const appState = AppState.addEventListener('change', state => { if (state === 'active') updateClock(); }); return () => { clearInterval(timer); appState.remove(); }; }, []));
  const range = customStart ? { start: customStart, end: now } : periodRange(period, previous, now);
  const report = buildReport(movements, selected?.initialBalance ?? 0, range.start, range.end);
  if (!selected) return <Screen><Header title="Resumen" /></Screen>;
  const rangeLabel = customStart ? `${customStart.toLocaleString('es-ES')} — ahora` : period === 'day' ? date(range.start) : `${date(range.start)} — ${date(new Date(range.end.getTime() - 1))}`;
  const openingLabel = customStart ? 'Balance inicial del corte' : period === 'day' ? 'Balance inicial del día' : period === 'week' ? 'Balance inicial de la semana' : 'Balance inicial del mes';
  const reportPeriod = customStart ? `Corte: ${rangeLabel}` : `${periodNames[period]}: ${rangeLabel}`;
  const changeStart = (event: DateTimePickerEvent, value?: Date) => { setPicker(null); if (event.type === 'dismissed' || !value) return; const next = new Date(customStart ?? new Date()); if (picker === 'date') next.setFullYear(value.getFullYear(), value.getMonth(), value.getDate()); else next.setHours(value.getHours(), value.getMinutes(), 0, 0); setCustomStart(next > new Date() ? new Date() : next); };
  const share = async () => { const exportNow = new Date(); const exportRange = customStart ? { start: customStart, end: exportNow } : periodRange(period, previous, exportNow); const exportReport = buildReport(movements, selected.initialBalance, exportRange.start, exportRange.end); const exportRangeLabel = customStart ? `${customStart.toLocaleString('es-ES')} — ahora` : period === 'day' ? date(exportRange.start) : `${date(exportRange.start)} — ${date(new Date(exportRange.end.getTime() - 1))}`; const exportPeriod = customStart ? `Corte: ${exportRangeLabel}` : `${periodNames[period]}: ${exportRangeLabel}`; try { await Share.share({ title: `Resumen de ${selected.name}`, message: formatReportText(selected.name, selected.currency, exportPeriod, exportReport) }); } catch (error) { Alert.alert('No se pudo exportar', error instanceof Error ? error.message : 'Inténtalo otra vez.'); } };
  return <Screen><Header title="Resumen" /><Tabs value={period} onChange={(value) => { setPeriod(value); setPrevious(false); setCustomStart(null); }} options={[{ value: 'day', label: 'Día' }, { value: 'week', label: 'Semana' }, { value: 'month', label: 'Mes' }]} />
    <Card><Text style={styles.cutTitle}>Inicio del resumen</Text><Text style={styles.periodDate}>{customStart ? customStart.toLocaleString('es-ES') : 'Inicio automático del período'}</Text><View style={styles.cutActions}><Button label="Fecha" icon="calendar-outline" tone="ghost" onPress={() => setPicker('date')} /><Button label="Hora" icon="clock-outline" tone="ghost" onPress={() => setPicker('time')} />{customStart && <Button label="Restablecer" tone="danger" onPress={() => setCustomStart(null)} />}</View></Card>
    {picker && <DateTimePicker value={customStart ?? new Date()} mode={picker} display={Platform.OS === 'ios' ? 'compact' : 'default'} onChange={changeStart} maximumDate={new Date()} />}
    <View style={styles.periodRow}><View style={{ flex: 1 }}><Text style={styles.periodTitle}>{customStart ? 'Corte personalizado' : previous ? `${periodNames[period]} anterior` : `${periodNames[period]} actual`}</Text><Text style={styles.periodDate}>{rangeLabel}</Text></View>{!customStart && <Button label={previous ? 'Ver actual' : 'Ver anterior'} icon={previous ? 'calendar-today' : 'history'} tone="ghost" onPress={() => setPrevious(x => !x)} />}</View>
    <Card style={styles.hero}><View style={styles.openingRow}><Text style={styles.heroLabel}>{openingLabel}</Text><Text style={styles.openingValue}>{money(report.opening, selected.currency)}</Text></View><View style={styles.heroDivider} /><Text style={styles.heroLabel}>Balance al cierre</Text><Text adjustsFontSizeToFit numberOfLines={1} style={[styles.heroValue, report.closing < 0 && styles.heroNegative]}>{money(report.closing, selected.currency)}</Text></Card>
    <View style={styles.grid}><Card style={styles.metric}><View style={[styles.metricIcon, styles.in]}><MaterialCommunityIcons name="arrow-down" size={20} color={theme.colors.success} /></View><Text style={styles.metricLabel}>Depósitos</Text><Text style={[styles.metricValue, { color: theme.colors.success }]}>+{money(report.deposits, selected.currency)}</Text></Card><Card style={styles.metric}><View style={[styles.metricIcon, styles.out]}><MaterialCommunityIcons name="arrow-up" size={20} color={theme.colors.danger} /></View><Text style={styles.metricLabel}>Retiros</Text><Text style={[styles.metricValue, { color: theme.colors.danger }]}>−{money(report.withdrawals, selected.currency)}</Text></Card></View>
    <Card><View style={styles.line}><Text style={styles.lineLabel}>Cantidad de movimientos</Text><Text style={styles.lineValue}>{report.included.length}</Text></View>{selected.currency === 'USDT' && <><View style={styles.line}><Text style={styles.lineLabel}>CUP retirados con conversión</Text><Text style={styles.lineValue}>{money(report.cupWithdrawn, 'CUP')}</Text></View><View style={styles.line}><Text style={styles.lineLabel}>Retiros directos 1×1</Text><Text style={styles.lineValue}>{money(report.directWithdrawn, 'USDT')}</Text></View></>}<View style={styles.line}><Text style={styles.lineLabel}>Total de retiros</Text><Text style={[styles.lineValue, { color: theme.colors.danger }]}>{money(report.withdrawals, selected.currency)}</Text></View><View style={styles.line}><Text style={styles.lineLabel}>Variación neta</Text><Text style={[styles.lineValue, report.deposits - report.withdrawals < 0 && { color: theme.colors.danger }]}>{money(report.deposits - report.withdrawals, selected.currency)}</Text></View></Card>
    <Button label={loading ? 'Actualizando…' : 'Exportar resumen en texto'} icon="share-variant-outline" tone="ghost" onPress={share} disabled={loading} />
  </Screen>;
}
const styles = StyleSheet.create({ cutTitle: { ...theme.type.label }, cutActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 }, periodRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, periodTitle: { ...theme.type.section }, periodDate: { ...theme.type.caption, color: theme.colors.muted, marginTop: 2 }, hero: { backgroundColor: theme.colors.primary }, openingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, openingValue: { ...theme.type.label, color: theme.colors.white }, heroDivider: { height: 1, backgroundColor: 'rgba(255,255,255,0.13)', marginVertical: 13 }, heroLabel: { ...theme.type.caption, color: '#BFC8D7' }, heroValue: { fontSize: 32, lineHeight: 40, fontWeight: '800', color: theme.colors.gold, marginTop: 5 }, heroNegative: { color: '#FF8A8A' }, grid: { flexDirection: 'row', gap: 12 }, metric: { flex: 1, minWidth: 0 }, metricIcon: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginBottom: 10 }, in: { backgroundColor: theme.colors.successSoft }, out: { backgroundColor: theme.colors.dangerSoft }, metricLabel: { ...theme.type.caption, color: theme.colors.muted }, metricValue: { ...theme.type.section, marginTop: 3 }, line: { minHeight: 43, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, borderBottomWidth: 1, borderBottomColor: theme.colors.border }, lineLabel: { ...theme.type.body, color: theme.colors.muted, flex: 1 }, lineValue: { ...theme.type.label, textAlign: 'right' } });
